package master;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import com.mysql.jdbc.Statement;
import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
/**
 *
 * @author Abin
 */
public class menu extends javax.swing.JFrame {
Connection koneksi;
public static int kodeLogin=3;
ResultSet resultSet;
Statement statement;


    /**
     * Creates new form menu
     */
    
     public menu(String Username, String UserRole) {
        initComponents();
         this.setSize(1366,768);             
        user.setEnabled(true);             
        data.setVisible(false);             
        data.setEnabled(false);             
        user.setEnabled(true);                    
        keluar.setEnabled(true); 
        
        setExtendedState(MAXIMIZED_BOTH); 
        admin.setForeground(Color.red);
         kata.setText("Selamat datang di Poliklinik Mitra Medika");         
         admin.setText(Username);         
         kata.setEditable(false);
         
         if("Admin".equals(UserRole)){             
             kata.setText("Selamat datang. Anda login sebagai " + UserRole + "");             
             admin.setText(Username);
             user.setEnabled(true);
             data.setVisible(true);             
             data.setEnabled(true);             
             user.setEnabled(true);  
             LogIn.setVisible(false);
             keluar.setEnabled(true);         
         } else if ("Petugas".equals(UserRole)) {
              kata.setText("Selamat datang. Anda login sebagai " + UserRole + "");             
              admin.setText(Username);             
              user.setEnabled(true);             
              data.setVisible(true);             
              data.setEnabled(true);             
              user.setVisible(false);            
              LogIn.setVisible(false);
              keluar.setEnabled(true);         
         }    else if ("".equals(UserRole)) {
              kata.setText("Selamat datang. Anda login sebagai Pengunjung");             
              admin.setText(Username);             
              user.setEnabled(true);             
              data.setVisible(false);             
              data.setEnabled(false);             
              user.setVisible(true);     
              LogOut.setVisible(false);
              keluar.setEnabled(true);         
         }   

}   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jProgressBar1 = new javax.swing.JProgressBar();
        admin = new javax.swing.JLabel();
        kata = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        user = new javax.swing.JMenu();
        LogIn = new javax.swing.JMenuItem();
        NewUser = new javax.swing.JMenuItem();
        LogOut = new javax.swing.JMenuItem();
        data = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        keluar = new javax.swing.JMenu();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        admin.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        admin.setText("ADMIN");

        kata.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N

        jMenuBar1.setMargin(new java.awt.Insets(2, 0, 0, 0));

        user.setText("User");
        user.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        LogIn.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        LogIn.setText("Login");
        LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInActionPerformed(evt);
            }
        });
        user.add(LogIn);

        NewUser.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        NewUser.setText("NewUser");
        NewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewUserActionPerformed(evt);
            }
        });
        user.add(NewUser);

        LogOut.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        LogOut.setText("Logout");
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });
        user.add(LogOut);

        jMenuBar1.add(user);

        data.setText("Data");
        data.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jMenuItem1.setText("Pegawai");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        data.add(jMenuItem1);

        jMenuBar1.add(data);

        keluar.setText("Exit");
        keluar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        jMenuBar1.add(keluar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(admin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(kata, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(admin)
                .addGap(148, 148, 148)
                .addComponent(kata, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(245, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewUserActionPerformed
        // TODO add your handling code here:
        new NewUser().setVisible(true);
        dispose();
    }//GEN-LAST:event_NewUserActionPerformed

    private void LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInActionPerformed
        // TODO add your handling code here:
        new login().setVisible(true);
        dispose();
    }//GEN-LAST:event_LogInActionPerformed

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        // TODO add your handling code here:
        new login().setVisible(true);
        dispose();
    }//GEN-LAST:event_LogOutActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        dispose();
    }//GEN-LAST:event_keluarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Object[]options = {"YA","TIDAK"};    
           int konfirmasi=JOptionPane.showOptionDialog(null,"Anda ingin beralih ke form pegawai?",
                   "Konfirmasi",
                   JOptionPane.YES_NO_OPTION,
                   JOptionPane.QUESTION_MESSAGE,
                   null,options,options[0]);         
           if(konfirmasi==JOptionPane.YES_OPTION){ 
        new Pegawai().setVisible(true);
    
           }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu("","").setVisible(true);
            }
        });
    }
    
    private void belumLogin() {
        data.setEnabled(false);
        keluar.setEnabled(true); 
 }
    private void loginAdmin() {
        data.setEnabled(true);
        user.setVisible(false);
 }
    private void loginPetugas() {
        data.setEnabled(true);
        user.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem LogIn;
    private javax.swing.JMenuItem LogOut;
    private javax.swing.JMenuItem NewUser;
    private javax.swing.JLabel admin;
    private javax.swing.JMenu data;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField kata;
    private javax.swing.JMenu keluar;
    private javax.swing.JMenu user;
    // End of variables declaration//GEN-END:variables
}
