
import jaco.mp3.player.MP3Player;
import java.io.File;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author arilc
 */
public class MP3 extends javax.swing.JFrame {

    public MP3Player mp3player;
    DefaultListModel model = new DefaultListModel();

    /**
     * Creates new form MP3Player
     */
    public MP3() {
        initComponents();
        setLocationRelativeTo(null);
        setSize(550,360);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        daftar = new javax.swing.JList();
        play = new javax.swing.JButton();
        buka = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Spotipy");
        setMaximumSize(new java.awt.Dimension(410, 536));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(daftar);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 370, 100));

        play.setIcon(new javax.swing.ImageIcon("D:\\Unduhan\\icon netbeans\\icons8-play-button-circled-50.png")); // NOI18N
        play.setBorder(null);
        play.setBorderPainted(false);
        play.setFocusPainted(false);
        play.setIconTextGap(0);
        play.setMargin(new java.awt.Insets(0, 0, 0, 0));
        play.setName("Play"); // NOI18N
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });
        getContentPane().add(play, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 60, 60));

        buka.setIcon(new javax.swing.ImageIcon("D:\\Unduhan\\icon netbeans\\icons8-import-50.png")); // NOI18N
        buka.setBorder(null);
        buka.setBorderPainted(false);
        buka.setContentAreaFilled(false);
        buka.setFocusPainted(false);
        buka.setIconTextGap(0);
        buka.setMargin(new java.awt.Insets(0, 0, 0, 0));
        buka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bukaActionPerformed(evt);
            }
        });
        getContentPane().add(buka, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 60, 50));

        keluar.setBackground(new java.awt.Color(255, 0, 51));
        keluar.setIcon(new javax.swing.ImageIcon("D:\\Unduhan\\icon netbeans\\icons8-shutdown-50.png")); // NOI18N
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 60, 60));

        hapus.setBackground(new java.awt.Color(255, 153, 51));
        hapus.setIcon(new javax.swing.ImageIcon("D:\\Unduhan\\icon netbeans\\icons8-remove-50.png")); // NOI18N
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 60, 60));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Playlist");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 80, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("D:\\Unduhan\\icon netbeans\\icons8-spotify-48.png")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Unduhan\\icon netbeans\\Voice recognition.gif")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 200, 690, 170));

        bg.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        bg.setForeground(new java.awt.Color(255, 255, 255));
        bg.setIcon(new javax.swing.ImageIcon("C:\\Users\\arilc\\OneDrive\\Pictures\\Screenshot\\Screenshot (7).png")); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        if (daftar.getSelectedIndex() != -1) {
            String musik = daftar.getSelectedValue().toString();
            if (play.getName().equals("Play")) {
                try {
                    mp3player = new MP3Player(new File(musik));
                    mp3player.play();
                } catch (Exception e) {
                }
                play.setName("Stop");
                play.setIcon(new javax.swing.ImageIcon(getClass().getResource("icon/icons8-pause-button-50.png")));

            } else {
                mp3player.stop();
                play.setName("Play");
                play.setIcon(new javax.swing.ImageIcon(getClass().getResource("icon/icons8-play-button-circled-50.png")));
            }
        } else {
            JOptionPane.showMessageDialog(null, "Tidak ada lagu yang dipilih");
        }
    }//GEN-LAST:event_playActionPerformed

    private void bukaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bukaActionPerformed
        JFileChooser fc = new JFileChooser();
        JFrame jf = new JFrame();

        FileNameExtensionFilter Filemp3 = new FileNameExtensionFilter(".mp4,.wav", "mp3", "wav");
        fc.addChoosableFileFilter(Filemp3);
        fc.setCurrentDirectory(new File("C:/Users/arilc/Music"));

        int setuju = fc.showOpenDialog(jf.add(fc));
        int posisi = daftar.getModel().getSize();
        if (setuju == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            String text = file.getPath().toString();
            String[] txt = new String[]{text};
            model.add(posisi, text);
        }
        daftar.setModel(model);
    }//GEN-LAST:event_bukaActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, "Keluar?", "Konfirmasi", 0);
        if (confirm == 0){}
        System.exit(0);
    }//GEN-LAST:event_keluarActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        int posisi = daftar.getSelectedIndex();
        if (posisi != -1) {
            model.remove(posisi);
        } else {
            JOptionPane.showMessageDialog(null, "Pilih daftar yang ingin di hapus");
        }
    }//GEN-LAST:event_hapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MP3Player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MP3Player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MP3Player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MP3Player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MP3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton buka;
    private javax.swing.JList daftar;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton keluar;
    private javax.swing.JButton play;
    // End of variables declaration//GEN-END:variables
}
