package master;


import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JLabel;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author ghostman
 * @author TAUFIQ_ART
 * INPUT DATA SISWA WITH MYSQL DATABASE
 _____  _   _   _ _____ ___ ___          _    ____ _____ 
|_   _|/ \ | | | |  ___|_ _/ _ \        / \  |  _ \_   _|
  | | / _ \| | | | |_   | | | | |_____ / _ \ | |_) || |  
  | |/ ___ \ |_| |  _|  | | |_| |_____/ ___ \|  _ < | |  
  |_/_/   \_\___/|_|   |___\__\_\    /_/   \_\_| \_\|_|

 */
public class input_data_siswa extends javax.swing.JFrame {

    /**
     * Creates new form input_data_siswa
     */
    
    public input_data_siswa() {
        initComponents();
        tglskrg();
        getData("SELECT * FROM siswa","Koneksi Database Berhasil","Koneksi Database gagal");
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        cmdjurusan.setOpaque(false);
//        jScrollPane1.setBorder();
        jScrollPane1.setViewportBorder(null);
        cmdjurusan.setBorder(null);
        

    }
    public void manData(String query, String success, String error){
        try {            
            Connection con = (Connection) Koneksi.getConnection();
            PreparedStatement pst = con.prepareStatement(query);
            pst.execute();
            JOptionPane.showMessageDialog(null, success);
            clear();
            if(!query.contains("SELECT")){
                getData("SELECT * FROM siswa","null","null");
            }            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, error+"\n"+e.getMessage());
        }
    }
    public void getData(String query, String success, String error){
        
        ((DefaultTableCellRenderer) jtabel.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        try {
            Statement st = (Statement) Koneksi.getConnection().createStatement();
            ResultSet rs = st.executeQuery(query);
            rs.last();
            if(rs.getRow()==0){                
                DefaultTableModel tbl = new DefaultTableModel();
                tbl.addColumn("DATA TIDAK DI TEMUKAN");
                jtabel.setModel(tbl);
                
            }else{
                rs.beforeFirst();
                DefaultTableModel tbl = new DefaultTableModel();
                tbl.addColumn("NIS");
                tbl.addColumn("NAMA");
                tbl.addColumn("JENIS KELAMIN");
                tbl.addColumn("JURUSAN");
                tbl.addColumn("ALAMAT");
                DefaultTableCellRenderer center = new DefaultTableCellRenderer();
                center.setHorizontalAlignment(JLabel.CENTER);                
                while(rs.next()){
                    tbl.addRow(new Object[] {
                        rs.getString("nis"),
                        rs.getString("nama"),
                        rs.getString("jenkel"),
                        rs.getString("jurusan"),
                        rs.getString("alamat")
                    });                    
                    jtabel.setModel(tbl);
                }
            }
            
            if(!success.equals("null")){
                JOptionPane.showMessageDialog(null, success);
            }            
        } catch (Exception e) {
            if(!error.equals("null")){
                JOptionPane.showMessageDialog(null, error +"\n"+e.getMessage());
                System.exit(0);
            }
        }          
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jenisKelamin = new javax.swing.ButtonGroup();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txttgl = new javax.swing.JLabel();
        txtnis = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        rdlaki = new javax.swing.JRadioButton();
        rdperempuan = new javax.swing.JRadioButton();
        cmdjurusan = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtcari = new javax.swing.JTextField();
        cari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtalamat = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtabel = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        cmdsimpan = new javax.swing.JButton();
        cmdubah = new javax.swing.JButton();
        cmdhapus = new javax.swing.JButton();
        cmdkeluar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jButton6.setText("jButton6");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new Color(0,0,0,70));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new Color(0,0,0,70));
        jPanel2.setOpaque(false);

        jLabel2.setText("NIS");

        jLabel3.setText("NAMA");

        jLabel4.setText("JENIS KELAMIN");

        jLabel5.setText("JURUSAN");

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setText("DATA SISWA");

        txttgl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txttgl.setText("TANGGAL");

        txtnis.setBackground(new Color(0,0,0,1));
        txtnis.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        txtnama.setBackground(new Color(0,0,0,1));
        txtnama.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        jenisKelamin.add(rdlaki);
        rdlaki.setText("Laki-Laki");
        rdlaki.setContentAreaFilled(false);

        jenisKelamin.add(rdperempuan);
        rdperempuan.setText("Perempuan");

        cmdjurusan.setBackground(new java.awt.Color(0, 0, 153));
        cmdjurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KI 1", "KI 2", "KI 3", "KA 1", "KA 2", "TKJ 1", "TKJ 2", "TKJ 3", "MM 1", "MM 2", "MM 3", "RPL 1", "RPL 2", "OTKP 1", "OTKP 2", "AKL 1", "AKL 2", "AKL 3", "BDP 1", "BDP 2" }));
        cmdjurusan.setOpaque(false);

        jLabel7.setText("ALAMAT");

        txtcari.setBackground(new Color(0,0,0,1));
        txtcari.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcari.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcariKeyReleased(evt);
            }
        });

        cari.setText("CARI");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new Color(0,0,0,1));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setOpaque(false);

        txtalamat.setBackground(new Color(0,0,0,1));
        txtalamat.setColumns(20);
        txtalamat.setRows(5);
        txtalamat.setTabSize(4);
        txtalamat.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jScrollPane1.setViewportView(txtalamat);

        jtabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIS", "NAMA", "JENIS KELAMIN", "JURUSAN", "ALAMAT"
            }
        ));
        jtabel.setGridColor(new java.awt.Color(91, 91, 96));
        jtabel.setOpaque(false);
        jtabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtabelMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jtabel);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        cmdsimpan.setText("SIMPAN");
        cmdsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdsimpanActionPerformed(evt);
            }
        });

        cmdubah.setText("UBAH");
        cmdubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdubahActionPerformed(evt);
            }
        });

        cmdhapus.setText("HAPUS");
        cmdhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdhapusActionPerformed(evt);
            }
        });

        cmdkeluar.setText("KELUAR");
        cmdkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdkeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmdsimpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdubah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdhapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdkeluar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdsimpan)
                    .addComponent(cmdubah)
                    .addComponent(cmdhapus)
                    .addComponent(cmdkeluar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtnama)
                        .addComponent(txtnis)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(cmdjurusan, 0, 192, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rdlaki, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rdperempuan)))
                .addGap(155, 155, 155))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txttgl, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel6)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(txttgl))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rdlaki)
                    .addComponent(rdperempuan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdjurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 450));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel4.setBackground(new Color(0,0,0,60));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 450));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void clear(){
        txtnis.setText("");
        txtnama.setText("");
        rdlaki.setSelected(false);
        rdperempuan.setSelected(false);
        cmdjurusan.setSelectedIndex(0);
        txtalamat.setText("");
        txtcari.setText("");
    }
    private void cmdsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdsimpanActionPerformed

        String jk = "";
        if(rdlaki.isSelected()){
            jk = "Laki-Laki";
        }else if(rdperempuan.isSelected()){
            jk = "Perempuan";
        }
        
        if(txtnis.getText().equals("")||txtnama.getText().equals("")||jk.equals("")||cmdjurusan.getSelectedItem().toString().equals("")){
            JOptionPane.showMessageDialog(null, "Harap di isi Semua");
        }else{
            String query = "INSERT INTO siswa VALUES ('"+ txtnis.getText() + "','"
                    + txtnama.getText() + "','"+jk+"','"+cmdjurusan.getSelectedItem().toString() + "','"
                    + txtalamat.getText() +"')";
            manData(query, "Data berhasil di tambahkan", "Data gagal di tambahkan");
        }
        
    }//GEN-LAST:event_cmdsimpanActionPerformed

    private void cmdubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdubahActionPerformed
        
        String jk = "";
        if(rdlaki.isSelected()){
            jk = "Laki-Laki";
        }else if(rdperempuan.isSelected()){
            jk = "Perempuan";
        }
        if(jtabel.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(null, "Pilih data yang akan di ubah");
        }else{
            if(txtnis.getText().equals("")||txtnama.getText().equals("")||jk.equals("")||cmdjurusan.getSelectedItem().toString().equals("")){
                JOptionPane.showMessageDialog(null, "Harap di isi Semua");
            }else{
                DefaultTableModel tabel = (DefaultTableModel) jtabel.getModel();
                String query = "UPDATE siswa SET nis='"+ txtnis.getText() 
                        + "', nama='" + txtnama.getText() + "',jenkel='"+jk
                        +"',jurusan='"+cmdjurusan.getSelectedItem().toString() 
                        + "', alamat='"+ txtalamat.getText() 
                        +"' WHERE nis='"+ tabel.getValueAt(jtabel.getSelectedRow(), 0).toString() + "'";
                manData(query, "Data berhasil di ubah", "Data gagal di ubah");
            }
        }
    }//GEN-LAST:event_cmdubahActionPerformed

    private void jtabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtabelMouseClicked

        DefaultTableModel tabel = (DefaultTableModel) jtabel.getModel();
        txtnis.setText(tabel.getValueAt(jtabel.getSelectedRow(), 0).toString());
        txtnama.setText(tabel.getValueAt(jtabel.getSelectedRow(), 1).toString());
        if(tabel.getValueAt(jtabel.getSelectedRow(), 2).toString().equals("Laki-Laki")){
            rdlaki.setSelected(true);
        }else{
            rdperempuan.setSelected(true);
        }
        cmdjurusan.setSelectedItem(tabel.getValueAt(jtabel.getSelectedRow(), 3).toString());
        txtalamat.setText(tabel.getValueAt(jtabel.getSelectedRow(), 4).toString());
    }//GEN-LAST:event_jtabelMouseClicked

    private void cmdhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdhapusActionPerformed

        if(jtabel.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(null, "Pilih data yang akan di hapus");
        }else{
            DefaultTableModel tabel = (DefaultTableModel) jtabel.getModel();
            String query = "DELETE FROM siswa WHERE nis='"+ tabel.getValueAt(jtabel.getSelectedRow(), 0).toString() + "'";
            manData(query, "Data berhasil di hapus", "Data gagal di hapus");

        }
    }//GEN-LAST:event_cmdhapusActionPerformed

    private void cmdkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdkeluarActionPerformed
        System.exit(0);
    
        if(JOptionPane.showConfirmDialog(null, "yakin ingin keluar!",null,0)==0){
            System.exit(0);
        }
    }//GEN-LAST:event_cmdkeluarActionPerformed
        
    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed

        txtcari.requestFocus();
        String query = "SELECT * FROM siswa WHERE nis LIKE '%"+txtcari.getText()
                +"%' OR nama LIKE '%"+txtcari.getText()+"%' OR jenkel LIKE '%"+txtcari.getText()
                +"%' OR jurusan LIKE '%"+txtcari.getText()+"%' OR alamat LIKE '%"+txtcari.getText()+"%'";
        getData(query,"null","null");
        
    }//GEN-LAST:event_cariActionPerformed

    private void txtcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyReleased

        String query = "SELECT * FROM siswa WHERE nis LIKE '%"+txtcari.getText()
                +"%' OR nama LIKE '%"+txtcari.getText()+"%' OR jenkel LIKE '%"+txtcari.getText()
                +"%' OR jurusan LIKE '%"+txtcari.getText()+"%' OR alamat LIKE '%"+txtcari.getText()+"%'";
        getData(query,"null","data null");
    }//GEN-LAST:event_txtcariKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(input_data_siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(input_data_siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(input_data_siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(input_data_siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new input_data_siswa().setVisible(true);
            }
        });
    }
    public void tglskrg(){
        Date skrg = new Date();
        SimpleDateFormat format = new SimpleDateFormat("dd MMMM yyyy");
        String tgl = format.format(skrg);
        txttgl.setText(tgl);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cari;
    private javax.swing.JButton cmdhapus;
    private javax.swing.JComboBox<String> cmdjurusan;
    private javax.swing.JButton cmdkeluar;
    private javax.swing.JButton cmdsimpan;
    private javax.swing.JButton cmdubah;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.ButtonGroup jenisKelamin;
    private javax.swing.JTable jtabel;
    private javax.swing.JRadioButton rdlaki;
    private javax.swing.JRadioButton rdperempuan;
    private javax.swing.JTextArea txtalamat;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnis;
    private javax.swing.JLabel txttgl;
    // End of variables declaration//GEN-END:variables
    private void setIconImage(String image) {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource(image)));
    }
}
