/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package master;
import com.mysql.jdbc.Statement;
import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import master.input_pegawai;
import master.User;
/**
 *
 * @author arilc
 */
public class menu extends javax.swing.JFrame {
Connection koneksi;
public static int kodeLogin=3;
ResultSet resultSet;
Statement statement;
    /**
     * Creates new form menu
     */
    public menu(String username, String typeuser) {
        initComponents();
        setLocationRelativeTo(null);
        user.setEnabled(true);             
        data.setVisible(false);             
        data.setEnabled(false);             
        user.setEnabled(true);                    
        keluar.setEnabled(true); 
        
        setExtendedState(MAXIMIZED_BOTH); 
        Login.setForeground(Color.red);
         kata.setText("Selamat datang di Poliklinik");         
         Login.setText(username);         
         
         if("Admin".equals(typeuser)){             
             kata.setText("Selamat datang. Anda login sebagai " + typeuser + "");             
             Login.setText(username);
             user.setEnabled(true);
             data.setVisible(true);             
             data.setEnabled(true);
             pegawai.setEnabled(true);
             pegawai.setVisible(true);
             user.setEnabled(true);  
             login.setVisible(false);
             keluar.setEnabled(true);         
         }else if ("Petugas".equals(typeuser)) {
              kata.setText("Selamat datang. Anda login sebagai " + typeuser + "");             
              Login.setText(username);             
              user.setEnabled(true);             
              data.setVisible(true);             
              data.setEnabled(true);             
              user.setVisible(false);            
              login.setVisible(false);
              keluar.setEnabled(true);         
         }else if ("".equals(typeuser)) {
              kata.setText("Selamat datang. Anda login sebagai Pengunjung");             
              Login.setText(username);             
              user.setEnabled(true);             
              data.setVisible(false);             
              data.setEnabled(false);             
              user.setVisible(false);     
              logout.setVisible(false);
              keluar.setEnabled(true);         
         }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kata = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Login = new javax.swing.JMenu();
        login = new javax.swing.JMenu();
        logout = new javax.swing.JMenu();
        user = new javax.swing.JMenu();
        newuser = new javax.swing.JMenu();
        data = new javax.swing.JMenu();
        pegawai = new javax.swing.JMenu();
        keluar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Poliklinik");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kata.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(kata, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 540, 30));

        jLabel2.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        jLabel2.setText("SELAMAT DATANG DI POLIKLINIK MITRA MEDIKA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\arilc\\OneDrive\\Pictures\\Saved Pictures\\rs.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Login.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        Login.setForeground(new java.awt.Color(51, 255, 255));
        Login.setIcon(new javax.swing.ImageIcon("D:\\Unduhan\\icon netbeans\\icons8-login-20.png")); // NOI18N
        Login.setText("LOGIN");
        Login.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        login.setIcon(new javax.swing.ImageIcon("D:\\Unduhan\\icon netbeans\\icons8-login-20.png")); // NOI18N
        login.setText("Login");
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });
        Login.add(login);

        logout.setIcon(new javax.swing.ImageIcon("D:\\Unduhan\\icon netbeans\\icons8-logout-rounded-left-20.png")); // NOI18N
        logout.setText("Log out");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        Login.add(logout);

        jMenuBar1.add(Login);

        user.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        user.setIcon(new javax.swing.ImageIcon("D:\\Unduhan\\icon netbeans\\icons8-users-settings-20.png")); // NOI18N
        user.setText("USER");
        user.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        newuser.setIcon(new javax.swing.ImageIcon("D:\\Unduhan\\icon netbeans\\icons8-add-user-male-20.png")); // NOI18N
        newuser.setText("Tambah User");
        newuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newuserMouseClicked(evt);
            }
        });
        user.add(newuser);

        jMenuBar1.add(user);

        data.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        data.setForeground(new java.awt.Color(102, 255, 102));
        data.setIcon(new javax.swing.ImageIcon("D:\\Unduhan\\icon netbeans\\icons8-file-20.png")); // NOI18N
        data.setText("DATA");
        data.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        pegawai.setIcon(new javax.swing.ImageIcon("D:\\Unduhan\\icon netbeans\\icons8-employee-20.png")); // NOI18N
        pegawai.setText("Pegawai");
        pegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pegawaiMouseClicked(evt);
            }
        });
        data.add(pegawai);

        jMenuBar1.add(data);

        keluar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        keluar.setForeground(new java.awt.Color(255, 51, 51));
        keluar.setIcon(new javax.swing.ImageIcon("D:\\Unduhan\\icon netbeans\\icons8-logout-15.png")); // NOI18N
        keluar.setText("KELUAR");
        keluar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        keluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keluarMouseClicked(evt);
            }
        });
        jMenuBar1.add(keluar);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void keluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keluarMouseClicked
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, "Keluar?", "Konfirmasi", 0);
        if (confirm == 0){System.exit(0);}
        Object[]options={"Ya","Tidak"};
        int konfirmasi=JOptionPane.showOptionDialog(null,"Apakah Anda Yakin Ingin Keluar?",
                "konfirmasi",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,options,options[0]);
        if(konfirmasi==JOptionPane.YES_OPTION) {
            new login().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_keluarMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setExtendedState(menu.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void newuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newuserMouseClicked
        // TODO add your handling code here:
         Object[]options = {"YA","TIDAK"};    
           int konfirmasi=JOptionPane.showOptionDialog(null,"Anda ingin beralih ke form pegawai?",
                   "Konfirmasi",
                   JOptionPane.YES_NO_OPTION,
                   JOptionPane.QUESTION_MESSAGE,
                   null,options,options[0]);         
           if(konfirmasi==JOptionPane.YES_OPTION){ 
        new User().setVisible(true);
           }
    }//GEN-LAST:event_newuserMouseClicked

    private void pegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pegawaiMouseClicked
        // TODO add your handling code here:
         Object[]options = {"YA","TIDAK"};    
           int konfirmasi=JOptionPane.showOptionDialog(null,"Anda ingin beralih ke form pegawai?",
                   "Konfirmasi",
                   JOptionPane.YES_NO_OPTION,
                   JOptionPane.QUESTION_MESSAGE,
                   null,options,options[0]);         
           if(konfirmasi==JOptionPane.YES_OPTION){ 
        new input_pegawai().setVisible(true);
           }
    }//GEN-LAST:event_pegawaiMouseClicked

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        // TODO add your handling code here:
        new login().setVisible(true);
    }//GEN-LAST:event_loginMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, "keluar?", "konfirmasi", 0);
        if (confirm==0){
            dispose();
        }
    }//GEN-LAST:event_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu("","").setVisible(true);
            }
        });
    }
private void belumLogin() {
        data.setEnabled(false);
        keluar.setEnabled(true); 
 }
    private void loginAdmin() {
        data.setEnabled(true);
        user.setVisible(false);
 }
    private void loginPetugas() {
        data.setEnabled(true);
        user.setVisible(false);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Login;
    private javax.swing.JMenu data;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel kata;
    private javax.swing.JMenu keluar;
    private javax.swing.JMenu login;
    private javax.swing.JMenu logout;
    private javax.swing.JMenu newuser;
    private javax.swing.JMenu pegawai;
    private javax.swing.JMenu user;
    // End of variables declaration//GEN-END:variables
}
